#!/bin/bash

if [ -z "$1" ]; then
    echo "$0 [mixin .java file] [target .java file]"
    exit 1
fi

if [ -z "$2" ]; then
    echo "$0 [mixin .java file] [target .java file]"
    exit 1
fi

FIELDS=$(
    echo | \
        sed -e '/\/\/#region Autogenerated Shadows/,/\/\/#endregion Autogenerated Shadows/ { r /dev/stdin' -e '; //!d }' $1 | \
        CLASS_FILTER=AUTO OPERATION=list-fields python3 ./get_shadows.py | \
        paste -sd "," -
)

METHODS=$(
    echo | \
        sed -e '/\/\/#region Autogenerated Shadows/,/\/\/#endregion Autogenerated Shadows/ { r /dev/stdin' -e '; //!d }' $1 | \
        CLASS_FILTER=AUTO OPERATION=list-methods python3 ./get_shadows.py | \
        paste -sd "," -
)

CLASS_FILTER=AUTO OPERATION=shadows FIELD_BLACKLIST=$FIELDS METHOD_BLACKLIST=$METHODS python3 ./get_shadows.py <$2 | \
    sed -i.backup -e '/\/\/#region Autogenerated Shadows/,/\/\/#endregion Autogenerated Shadows/ { r /dev/stdin' -e '; //!d }' $1
